### PR TITLE
support keeping conversation history, we can do multi-round conversation now;  support websocket stream now.

### PR DESCRIPTION
**Pull request by yuanzhanghu**
support keeping conversation history, we can do multi-round conversation now;  support websocket stream now.

Please add these fields in body to support conversation history: 

--data '{
  "model": "gpt-4",
  "parent_message_id: xxx,   // client need to save 'message_id' from response message, and use it here.
  "conversation_id": xxx, // client need to save 'conversation_id' from response message, and use it here.
  "history_disabled": false,   // to enable conversation history.
  "messages": [{"role": "user", "content": "test"}],
  "stream": true
}'

websocket stream was tested successfully.

### CODE REVIEW

**Comment by yuanzhanghu** [comment]
看起来send_conversation和send_conversation_for_stream合并了？  这个可能还需要作者帮忙修改下，看看怎么合并新的stream和非stream函数。

**Comment by LanQian528** [comment]
Thank you for your pr!

Perhaps whether to return the conversation_id should be a configuration option?

**Comment by LanQian528** [comment]
Now it is possible to directly transmit historical records just like an API.

**Comment by LanQian528** [comment]
Now you can control whether to return the ID by the environment variable `history_enable`.

**Pull request merged**
